export const mockJobs = [
  {
    id: "1",
    company: "Myntra",
    openings: "100 Openings",
    timeAgo: "1d ago",
    description: "Create UGC Videos and get shares on Instagram about Myntra Showbizz now.",
    payment: "₹ 350",
    applicationDeadline: "2025-02-15",
  },
  {
    id: "2",
    company: "Amazon",
    openings: "50 Openings",
    timeAgo: "2d ago",
    description: "Product testing and feedback for new Amazon devices.",
    payment: "₹ 500",
    applicationDeadline: "2025-03-01",
  },
  {
    id: "3",
    company: "Zomato",
    openings: "75 Openings",
    timeAgo: "1d ago",
    description: "Food delivery and customer service for Zomato orders.",
    payment: "₹ 250",
    applicationDeadline: "2025-02-20",
  },
  {
    id: "4",
    company: "Swiggy",
    openings: "120 Openings",
    timeAgo: "3d ago",
    description: "Delivery partner for Swiggy food orders in your area.",
    payment: "₹ 200",
    applicationDeadline: "2025-02-28",
  },
  {
    id: "5",
    company: "Uber",
    openings: "80 Openings",
    timeAgo: "1d ago",
    description: "Ride sharing service partner for Uber in your city.",
    payment: "₹ 300",
    applicationDeadline: "2025-03-10",
  },
  {
    id: "6",
    company: "Ola",
    openings: "90 Openings",
    timeAgo: "2d ago",
    description: "Cab driving service partner for Ola in your city.",
    payment: "₹ 280",
    applicationDeadline: "2025-03-05",
  },
  {
    id: "7",
    company: "Flipkart",
    openings: "60 Openings",
    timeAgo: "1d ago",
    description: "Product photography and cataloging for Flipkart products.",
    payment: "₹ 400",
    applicationDeadline: "2025-02-25",
  },
  {
    id: "8",
    company: "Snapdeal",
    openings: "40 Openings",
    timeAgo: "4d ago",
    description: "Customer support and order processing for Snapdeal.",
    payment: "₹ 320",
    applicationDeadline: "2025-03-15",
  },
  {
    id: "9",
    company: "BigBasket",
    openings: "55 Openings",
    timeAgo: "1d ago",
    description: "Grocery delivery and inventory management for BigBasket.",
    payment: "₹ 275",
    applicationDeadline: "2025-03-01",
  },
];
